version: '3.8'
services:
    manager:
        image: manager
        build: 
            context: ./crackhash-manager/
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            rabbitmq:
                condition: service_healthy
    worker-1:
        image: worker
        build: 
            context: ./crackhash-worker/
            dockerfile: Dockerfile
        ports:
            - "0:8080"
        depends_on:
            rabbitmq:
                condition: service_healthy
    worker-2:
        image: worker
        build: 
            context: ./crackhash-worker/
            dockerfile: Dockerfile
        ports:
            - "0:8080"
        depends_on:
            rabbitmq:
                condition: service_healthy
    worker-3:
        image: worker
        build: 
            context: ./crackhash-worker/
            dockerfile: Dockerfile
        ports:
            - "0:8080"
        depends_on:
            rabbitmq:
                condition: service_healthy
    db:
        image: mongo:7-jammy
        restart: unless-stopped
        ports:
            - "27017:27017"
        entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,db"]
    db-sec1:
        image: mongo:7-jammy
        restart: unless-stopped
        ports:
            - "27018:27017"
        entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,db-sec1"]
    db-sec2:
        image: mongo:7-jammy
        restart: unless-stopped
        ports:
            - "27019:27017"
        entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,db-sec2"]
    db-setup:
        image: db
        build:
            context: ./db
            dockerfile: Dockerfile
        restart: "no"
        depends_on:
            - db-sec1
            - db-sec2
            - db
    rabbitmq:
        image: rabbitmq:3-management-alpine
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        ports:
            - "5672:5672"
            - "15672:15672"
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 15s
            timeout: 15s
            retries: 5